# Generated by Django 5.2.4 on 2025-07-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SimilarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='catalog.category')),
                ('category_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='catalog.category')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='catalog_cat_parent__5307be_idx'),
        ),
        migrations.AddIndex(
            model_name='similarcategory',
            index=models.Index(fields=['category_a'], name='catalog_sim_categor_3e43bf_idx'),
        ),
        migrations.AddIndex(
            model_name='similarcategory',
            index=models.Index(fields=['category_b'], name='catalog_sim_categor_b556fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='similarcategory',
            unique_together={('category_a', 'category_b')},
        ),
    ]
