# Generated by Django 5.2.4 on 2025-07-30 13:26

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=catalog.models.get_default_image, null=True, upload_to='category_images/', validators=[catalog.models.validate_image_size]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
    ]
