# Generated by Django 5.2.4 on 2025-07-31 11:27

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_image_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=catalog.models.get_default_image, null=True, upload_to='category_images/uploaded_images/', validators=[catalog.models.validate_image_size]),
        ),
    ]
